# Generated by Django 4.0 on 2021-12-24 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('eed2f4f5-2aea-46dd-82d5-ebc1e2ae6d35'), primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
