# Generated by Django 4.0 on 2022-01-01 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c644ab18-4abf-49fc-a058-1e15b78dd397'), primary_key=True, serialize=False),
        ),
    ]
