# Generated by Django 4.0 on 2022-01-15 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('850df728-f96b-4c94-abaf-938e659be47a'), primary_key=True, serialize=False),
        ),
    ]
