# Generated by Django 4.0 on 2022-01-18 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3f24472-7ea2-49ae-906f-a235d14a0ce4'), primary_key=True, serialize=False),
        ),
    ]
