# Generated by Django 4.0 on 2022-01-18 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45ed2f13-16e1-4699-830a-e7c4e01dc24c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('346b814f-b933-4780-8342-f823124793f1'), primary_key=True, serialize=False),
        ),
    ]
